#!/usr/bin/env python
Import("env")
Import("env_modules")

env_mgs_nocode = env_modules.Clone()
env_mgs_nocode.add_source_files(env.modules_sources, "*.cpp")

if env.editor_build:
    env_mgs_nocode.add_source_files(env.modules_sources, "editor/*.cpp")
